project:
  type: website
  output-dir: docs
  
website:
  back-to-top-navigation: true
  page-footer: 
    center: "Copyright 2025, Tipsarp Kittisiam" 
  title: "A Blog About Veterinarian Mental Well-being"
  navbar:
    left: 
      - icon: bookmark-heart-fill
        href: index.qmd
    right:
      - href: about.qmd
        text: About the Blog
      - text: About the Author
        href: https://minnie-kitt.github.io/

format:
  html:
    theme: yeti
    css: styles.css

editor: visual

