---
title: "About The Blog"
about:
  template: jolla
---

This blog was started in June 2025 as a way to break down findings from [my thesis](https://hdl.handle.net/10214/29012), into bite-sized chunks of information.

# Veterinary Feelings

Veterinary medicine is an [undeniably emotional profession](https://doi.org/10.1177/0891241611435099). Veterinarians are subject to emotional distress on a regular basis, whether that is their own emotions —*perhaps brought by the inevitable failure to save a patient—* or the clients’ emotions, such as losing a beloved pet. With this constant exposure to extremely emotional situations, it’s no wonder that many veterinarians experience [empathic distress](https://doi.org/10.1016/B0-08-043076-7/01739-3), eventually leading to [burnout](https://doi.org/10.1080/00480169.2019.1669504) and, in some cases, leaving the profession.

In 2022-2023, I interviewed 21 early-career veterinarians in Canada, asking them about emotional experiences in their clinical practice as part of my doctoral thesis research, now published as the article, ["A qualitative exploration of the emotional experiences and applications of emotional intelligence in early-career veterinarians"](https://doi.org/10.1002/vetr.5599).

"Veterinary Feelings" is the first [series](https://minnie-kitt.github.io/vmh-blog/#category=Veterinary%20Feelings) of blog posts which I translate the findings from this article, into a less academic and more reader-friendly experience.
