---
title: "Veterinarian Mental Well-being"
author: Tipsarp Kittisiam
description: "A brief review in 2025"
date: "6/26/2025"
categories:
  - review
---

# Veterinarian Mental Well-being

## A brief review in 2025

Veterinarians' poor mental health and well-being not only impact themselves but can also have perceived negative impacts on interactions with clients, teamwork, concentration, and decision-making, all of which can decrease the quality of care that patients receive.

From the employers' perspective, the veterinarians' poor mental health and well-being increase the chances of absenteeism, attrition, and turnover, which could present significant economic costs.

[A study in 2022](https://doi.org/10.3389/fvets.2022.814104) estimated that the turnover and reduced working hours caused by burnout contributed to at least \$1 - 2 billion in lost revenue annually in the U.S.

In 1980, [Blair and Hayes](https://doi.org/10.1002/ijc.2910250203) discovered that veterinary professionals had higher suicide rates compared to the average population. Over 40 years and potentially hundreds of published studies later, *what have we learned*? And, more importantly, *where are we headed next*?

## Adverse effects of being a veterinarian

Firstly, we've learned the common *"adverse mental health outcomes"* associated with being a veterinary professional (not unlike those of the drugs that vets prescribe to their patients). Those include stress, anxiety, depression, and burnout, to name a few.

We've learned that suicide and suicidal ideation remain prevalent in the profession, despite efforts from organizations such as [Not One More Vet (NOMV)](https://nomv.org/) and others. Though we believe the situation to have improved, we currently don't have the research to support it.

We've also learned that these concerns exist in many countries around the world, as reported in, for example, the US, Canada, the UK, Australia, New Zealand, and the Netherlands. It's important to highlight that the absence of reports in other countries does not mean the concerns do not exist, but that they were simply not reported.

## ... but why?

These *"adverse mental health outcomes"* have been found to be tied to occupational stressors such as long work hours, poor work-life balance, professional mistakes, unexpected outcomes, and ethical dilemmas.

Newer studies have shown that the leadership and team environment play a pivotal role in making these stressors better or worse. For example, [a focus group with veterinary technicians](https://doi.org/10.3389/fvets.2015.00078) revealed that teams with toxic work environments also came with excessive workload, leading to burnout and staff turnover.

## Shifting away from the adverse outcomes

While previous research has done a lot to uncover the concerns of mental health and well-being in the profession, there has been a collective shift to move away from that narrative.

In 2017, [Cake](https://doi.org/10.3138/jvme.0116-025R) advocated for more research that focuses on the positive aspects of veterinary work (*which has always been eclipsed by the negatives in the past*). A lot of veterinarians (*myself included*) love the profession, despite all the adverse effects that may come with it.

Like most prescription drugs, pharmaceutical corporations innovate newer generations of drugs that become more effective while reducing the adverse effects. *What if we could do the same for the veterinary profession?*

As mental wellness practices and positive psychology become more mainstream, they have spilled over into veterinarian mental health as well. For example, my team has published research articles on [meaningful work](https://doi.org/10.3389/fvets.2025.1595949) and [emotional intelligence](https://doi.org/10.1002/vetr.5599).

As we move forward, I hope to see more research on the positive aspects of veterinary work and how we can make the profession more positive for everyone.

------------------------------------------------------------------------

# References

Bartram, D. J., Yadegarfar, G., & Baldwin, D. S. (2009a). A cross-sectional study of mental health and well-being and their associations in the UK veterinary profession. *Soc Psychiatry Psychiatr Epidemiol*, *44*(12), 1075-1085. <https://doi.org/10.1007/s00127-009-0030-8>

Bartram, D. J., Yadegarfar, G., & Baldwin, D. S. (2009b). Psychosocial working conditions and work-related stressors among UK veterinary surgeons. *Occup Med (Lond)*, *59*(5), 334-341. <https://doi.org/10.1093/occmed/kqp072>

Best, C. O., Perret, J. L., Hewson, J., Khosa, D. K., Conlon, P. D., & Jones-Bitton, A. (2020). A survey of veterinarian mental health and resilience in Ontario, Canada. *Can Vet J*, *61*(2), 166-172. <https://www.ncbi.nlm.nih.gov/pubmed/32020936>

Blokland, K., Coe, J. B., & Spitznagel, M. B. (2024). Veterinary team members experiencing high levels of burden transfer are more likely to report burnout and a less optimal psychosocial work environment. *J Am Vet Med Assoc*, *262*(3), 343-351. <https://doi.org/10.2460/javma.23.06.0354>

Cake, M. A., McArthur, M. M., Matthew, S. M., & Mansfield, C. F. (2017). Finding the balance: uncovering resilience in the veterinary literature. *J Vet Med Educ*, *44*(1), 95-105. <https://doi.org/10.3138/jvme.0116-025R>

Corrigan, V. K., Newman, R. L., Richmond, P., Strand, E. B., & Vaisman, J. M. (2024). The future of flourishing in veterinary medicine: a systems-informed positive psychology approach in veterinary education \[Review\]. *Front Vet Sci*, *11*, 1484412. <https://doi.org/10.3389/fvets.2024.1484412>

Fritschi, L., Morrison, D., Shirangi, A., & Day, L. (2009). Psychological well-being of Australian veterinarians. *Aust Vet J*, *87*(3), 76-81. <https://doi.org/10.1111/j.1751-0813.2009.00391.x>

Gardner, D. H., & Hini, D. (2006). Work-related stress in the veterinary profession in New Zealand. *N Z Vet J*, *54*(3), 119-124. <https://doi.org/10.1080/00480169.2006.36623>

Gilling, M. L., & Parkinson, T. J. (2009). The transition from veterinary student to practitioner: a "make or break" period. *J Vet Med Educ*, *36*(2), 209-215. <https://doi.org/10.3138/jvme.36.2.209>

Hatch, P. H., Winefield, H. R., Christie, B. A., & Lievaart, J. J. (2011). Workplace stress, mental health, and burnout of veterinarians in Australia. *Aust Vet J*, *89*(11), 460-468. <https://doi.org/10.1111/j.1751-0813.2011.00833.x>

Heath, T. J. (2008). Initial work experiences of veterinarians who graduated from Australian universities in 2005. *Aust Vet J*, *86*(9), 357-364. <https://doi.org/10.1111/j.1751-0813.2008.00337.x>

Jones-Bitton, A., Gillis, D., Peterson, M., & McKee, H. (2023). Latent burnout profiles of veterinarians in Canada: Findings from a cross-sectional study. *Vet Rec*, *192*(2), e2281. <https://doi.org/10.1002/vetr.2281>

Mastenbroek, N. J., Demerouti, E., van Beukelen, P., Muijtjens, A. M., Scherpbier, A. J., & Jaarsma, A. D. (2014). Measuring potential predictors of burnout and engagement among young veterinary professionals; construction of a customised questionnaire (the Vet-DRQ). *Vet Rec*, *174*(7), 168. <https://doi.org/10.1136/vr.101761>

Mastenbroek, N. J., Jaarsma, A. D., Demerouti, E., Muijtjens, A. M., Scherpbier, A. J., & van Beukelen, P. (2014). Burnout and engagement, and its predictors in young veterinary professionals: the influence of gender. *Vet Rec*, *174*(6), 144. <https://doi.org/10.1136/vr.101762>

McArthur, M. L., Andrews, J. R., Brand, C., & Hazel, S. J. (2017). The prevalence of compassion fatigue among veterinary students in Australia and the associated psychological factors. *J Vet Med Educ*, *44*(1), 9-21. <https://doi.org/10.3138/jvme.0116-016R3>

McKay, C. H., & Vaisman, J. M. (2023). Psychological safety, purpose, path, and partnership reduce associate veterinarian desire to leave current employment. *Journal of the American Veterinary Medical Association*, *261*(10), 1518-1524. <https://doi.org/10.2460/javma.23.03.0158>

Moore, I. C., Coe, J. B., Adams, C. L., Conlon, P. D., & Sargeant, J. M. (2015). Exploring the Impact of Toxic Attitudes and a Toxic Environment on the Veterinary Healthcare Team \[Original Research\]. *Frontiers in Veterinary Science*, *Volume 2 - 2015*. <https://doi.org/10.3389/fvets.2015.00078>

Moses, L., Malowney, M. J., & Wesley Boyd, J. (2018). Ethical conflict and moral distress in veterinary practice: A survey of North American veterinarians. *J Vet Intern Med*, *32*(6), 2115-2122. <https://doi.org/10.1111/jvim.15315>

Nett, R. J., Witte, T. K., Holzbauer, S. M., Elchos, B. L., Campagnolo, E. R., Musgrave, K. J., Carter, K. K., Kurkjian, K. M., Vanicek, C. F., O'Leary, D. R., Pride, K. R., & Funk, R. H. (2015). Risk factors for suicide, attitudes toward mental illness, and practice-related stressors among US veterinarians. *J Am Vet Med Assoc*, *247*(8), 945-955. <https://doi.org/10.2460/javma.247.8.945>

Perret, J. L., Best, C. O., Coe, J. B., Greer, A. L., Khosa, D. K., & Jones-Bitton, A. (2020). Prevalence of mental health outcomes among Canadian veterinarians. *J Am Vet Med Assoc*, *256*(3), 365-375. <https://doi.org/10.2460/javma.256.3.365>

Persson, K., Selter, F., Neitzke, G., & Kunzmann, P. (2020). Philosophy of a “good death” in small animals and consequences for euthanasia in animal law and veterinary practice. *Animals*, *10*(1). <https://doi.org/10.3390/ani10010124>

Platt, B., Hawton, K., Simkin, S., & Mellanby, R. J. (2012). Suicidal behaviour and psychosocial problems in veterinary surgeons: a systematic review. *Soc Psychiatry Psychiatr Epidemiol*, *47*(2), 223-240. <https://doi.org/10.1007/s00127-010-0328-6>

Reijula, K., Rasanen, K., Hamalainen, M., Juntunen, K., Lindbohm, M. L., Taskinen, H., Bergbom, B., & Rinta-Jouppi, M. (2003). Work environment and occupational health of Finnish veterinarians. *Am J Ind Med*, *44*(1), 46-57. <https://doi.org/10.1002/ajim.10228>

Sonneveld, D., Goverts, Y., Duijn, C., Camps, G., Bougie, R., & Mastenbroek, N. (2023). Dutch veterinary graduates leaving practice: A mixed-methods analysis of frequency and underlying reasons. *Vet Rec*, *192*(4), e2178. <https://doi.org/10.1002/vetr.2178>

Tran, L., Crane, M. F., & Phillips, J. K. (2014). The distinct role of performing euthanasia on depression and suicide in veterinarians. *J Occup Health Psychol*, *19*(2), 123-132. <https://doi.org/10.1037/a0035837>

Vande Griek, O. H., Clark, M. A., Witte, T. K., Nett, R. J., Moeller, A. N., & Stabler, M. E. (2018). Development of a taxonomy of practice-related stressors experienced by veterinarians in the United States. *J Am Vet Med Assoc*, *252*(2), 227-233. <https://doi.org/10.2460/javma.252.2.227>

Volk, J. O., Schimmack, U., Strand, E. B., Lord, L. K., & Siren, C. W. (2018). Executive summary of the Merck Animal Health Veterinary Wellbeing Study. *J Am Vet Med Assoc*, *252*(10), 1231-1238. <https://doi.org/10.2460/javma.252.10.1231>

Volk, J. O., Schimmack, U., Strand, E. B., Reinhard, A., Vasconcelos, J., Hahn, J., Stiefelmeyer, K., & Probyn-Smith, K. (2022). Executive summary of the Merck Animal Health Veterinarian Wellbeing Study III and Veterinary Support Staff Study. *J Am Vet Med Assoc*, *260*(12), 1547-1553. <https://doi.org/10.2460/javma.22.03.0134>
